STOEGE-19591 _helpers.tpl & app-cm.yaml refactoring
foxford/conference pull request #394
Opened 2023-01-13 09:26 UTC by SuslikDaRete

2023-01-17 13:34 UTC, manifest approved these changes

2023-01-17 13:34 UTC, manifest commented on chart/templates/app-cm.yaml
> +    {{- $audience := .audience }}
не понятно какая именно audience здесь

2023-01-17 13:34 UTC, manifest commented on chart/templates/_helpers.tpl
> +{{- $audience := . -}}
Здесь `audience` это `tenant`. А на выходе получается tenant user audience.

2023-01-17 15:07 UTC, SuslikDaRete commented on chart/templates/app-cm.yaml
> +    {{- $audience := .audience }}
это audience самого микросервиса

2023-01-17 15:07 UTC, SuslikDaRete commented on chart/templates/_helpers.tpl
> +{{- $audience := . -}}
обновил

2023-01-17 15:26 UTC, manifest approved these changes

2023-01-17 15:45 UTC, manifest requested changes

2023-01-17 15:45 UTC, manifest commented on chart/templates/app-cm.yaml
> +        {{ (list $accountLabel $.Values.app.svc.audience) | compact | join "." | quote }},
This entire `trusted` block seems to be a duplicate of the following one.

2023-01-17 15:49 UTC, manifest commented on chart/templates/_helpers.tpl
> +{{- if eq $env "p" }}
Shouldn't we return `$tenant` in this case?

2023-01-19 10:03 UTC, SuslikDaRete commented on chart/templates/app-cm.yaml
> +        {{ list $accountLabel $tenantObjectAudience | join "." | quote }},
Yeap, you're right
Fixed

2023-01-19 10:04 UTC, SuslikDaRete commented on chart/templates/app-cm.yaml
> +        {{ (list $accountLabel $.Values.app.svc.audience) | compact | join "." | quote }},
Nope. It's in different `if` conditions

2023-01-19 10:05 UTC, SuslikDaRete commented on chart/templates/_helpers.tpl
> +{{- if eq $env "p" }}
Not here. Rewrote the condition to make it clearer

2023-01-19 13:27 UTC, manifest commented on chart/templates/app-cm.yaml
> +    {{- $tenantObjectAudience := include "conference.tenantObjectAudience" (list $ .audience) }}
Why do we have `(list $ .audience)` instead of just `.audience` here?

2023-01-20 12:22 UTC, manifest approved these changes

2023-01-20 12:23 UTC, manifest approved these changes

2023-01-25 07:21 UTC, merged